[general]
import = ["/home/alexd/.alacritty/themes/oxycarbon.toml"]
[font]
size = 22
normal = {family= "FantasqueSansM Nerd Font Mono", style="italic"}
offset = {x=1,y=2}
[window]
opacity = 0.90
blur = true
