[general]
import = ["/Users/alexd/.alacritty/themes/orango.toml"]
[font]
size = 22
# normal = {family= "FantasqueSansM Nerd Font Mono", style="italic"}
normal = {family= "FantasqueSansM Nerd Font Mono"}
offset = {x=4,y=4}
