set prefix C-a
unbind-key C-b
bind-key C-a send-prefix
set -g mouse on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
set-option -g allow-rename off

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour green

# copy mode
setw -g mode-style 'bg=#888888 bold'

# panes
set -g pane-border-style 'fg=#888888'
set -g pane-active-border-style 'fg=#55ff33'

# statusbar
set -g default-terminal "screen-256color"
set -g status-bg "#181818"
set -g status-fg "#888888"
setw -g window-status-current-style "fg=#55ff55"
setw -g window-status-current-format ' #I #W #F '
set -g status-position bottom
set -g status-justify left

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=#888888'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-format '#[fg=#888888]#I:#[fg=#888888]#W#[fg=#888888]#F '

setw -g window-status-bell-style 'fg=#55ff33 bg=#181818 bold'

# messages
set -g message-style 'fg=#55ff33 bg=#181818 bold'

bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"

