[colors.bright]
  black = "0x665c54"
  blue = "0x83a598"
  cyan = "0x8ec07c"
  green = "0xb8bb26"
  magenta = "0xd3869b"
  red = "0xfb4934"
  white = "0xfbf1c7"
  yellow = "0xfabd2f"

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
  cursor = "0xd5c4a1"
  text = "0x1d2021"

# Normal colors
[colors.normal]
  black = "0x1d2021"
  blue = "0x83a598"
  cyan = "0x8ec07c"
  green = "0xb8bb26"
  magenta = "0xd3869b"
  red = "0xfb4934"
  white = "0xd5c4a1"
  yellow = "0xfabd2f"

# Base16 Gruvbox dark, hard 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https=//github.com/morhetz/gruvbox)
[colors.primary]
  background = "0x1d2021"
  foreground = "0xd5c4a1"
