# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors.primary]

background = "#101010"
foreground = "#ffffff"
bright_foreground = "#ffffff"

[colors.cursor]

text = "#888888"
cursor = "#ffffff"

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#303030"

[colors.normal]

black = "#101010"
red = "#ff5533"
green = "#55ff55"
yellow = "#888888"
blue = "#888888"
magenta = "#888888"
cyan = "#888888"
white = "#ffffff"

[colors.search.matches]

foreground = "#888888"
background = "#303030"

[colors.search.focused_match]

foreground = "#00ff00"
background = "#303030"

[colors.footer_bar]

background = "#303030"
foreground = "#00ff00"

[colors.hints.start]

foreground = "#00ff00"
background = "#303030"

[colors.hints.end]

foreground = "#00ff00"
background = "#303030"
