[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[colors.cursor]
text = "#161616"
cursor = "#f2f4f8"

[colors.normal]
black   = "#262626"
red     = "#ee5396"
green   = "#42be65"
yellow  = "#08bdba"
blue    = "#33b1ff"
magenta = "#be95ff"
cyan    = "#3ddbd9"
white   = "#dde1e6"

[colors.bright]
black   = "#525252"
red     = "#ff7eb6"
green   = "#42be65"
yellow  = "#08bdba"
blue    = "#78a9ff"
magenta = "#be95ff"
cyan    = "#3ddbd9"
white   = "#ffffff"

[colors.selection]
text = "#f2f4f8"
background = "#525252"
